server:
  host: 127.0.0.1
  port: 8080
  http2:
    enable: true
  ssl:
    enable: false
    path: test.jks
    password: '123456'
  uploads:
    limit: 2147483648
  static:
    enable: true
    cache:
      enable: true
  template:
    enable: true
    type: thymeleaf
    suffix: ".html"
cache:
  enable: true
  type: redis
